### ISSUE TITLE
DBCP2

### ISSUE THREAD

**Issue by insou22** [Jake-SA/frndz#1]
You should change to something other than DBCP2 for your ConnectionPooling like HikariCP. DBCP is very industrial and heavyweight, not something you would want in a Spigot plugin. If you need help with HikariCP, check my guide at https://www.spigotmc.org/threads/guide-using-a-connectionpool-in-your-plugins-finished.102864/
Also cut that static abuse young man

**Comment by Jake-SA** [comment]
Thanks. I'll check out HikariCP.

Also, I know 😂 I'll work on that soon.

Thanks.
